apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hello-pipelinerun-
spec:
  pipelineRef:
    name: hello
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
