apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hello-pipelinerun-
spec:
  PipelineSpec:
      tasks:
        - name: hello
          taskRef:
            name: hello
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
